//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.Configs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StaticFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StaticFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.Configs.StaticFiles", typeof(StaticFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Salary,Email,Subscription Date,Website
        ///1,d7d7b783-d723-4b46-808e-403a436f2960,Sheelagh,Cherianne,Seessel,Lubumbashi,Bangladesh,+(55) 11 2233-4455,9117.54,Sheelagh.Cherianne@mail.com,1904-12-30,Seessel.co.it
        ///2,4f892b4b-408c-42bd-87f1-138a436cc870,Agnese,Ferrell,Rillings,Mbabane,&quot;Moldova, Republic of&quot;,+(55) 11 2233-4455,8853,Agnese.Ferrell@mail.com,1976-05-07,Rillings.co.it
        ///3,f7ccd165-940b-45b5-9846-3d180878a6d7,Pearline,McNully,Modie,Laho [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string default_csv_file {
            get {
                return ResourceManager.GetString("default_csv_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;HasHeader&quot;: true,
        ///	&quot;Delimiter&quot;: &quot;,&quot;,
        ///	&quot;NotifyAfter&quot;: 10,
        ///	&quot;OutputPath&quot;: &quot;F:\\default_easy_etl.csv&quot;
        ///}.
        /// </summary>
        internal static string default_csv_writer_config {
            get {
                return ResourceManager.GetString("default_csv_writer_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {	
        ///	&quot;NotifyAfter&quot;: 10,
        ///	&quot;OutputPath&quot;: &quot;F:\\default_easy_etl.json&quot;,
        ///	&quot;IndentJson&quot;: true,
        ///	&quot;IsJsonl&quot;: false
        ///}.
        /// </summary>
        internal static string default_json_writer_config {
            get {
                return ResourceManager.GetString("default_json_writer_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;HasHeader&quot;: true,
        ///	&quot;Delimiter&quot;: &quot;,&quot;,
        ///	&quot;NotifyAfter&quot;: 10,
        ///	&quot;ColumnsConfig&quot;: [
        ///		{
        ///			&quot;Type&quot;: &quot;ParseColumnAction&quot;,
        ///			&quot;ColumnName&quot;: &quot;Index&quot;,
        ///			&quot;Position&quot;: 0,
        ///			&quot;IsHeader&quot;: false,
        ///			&quot;OutputName&quot;: &quot;Index&quot;,
        ///			&quot;OutputType&quot;: &quot;System.Int32&quot;
        ///		},
        ///		{
        ///			&quot;Type&quot;: &quot;ParseColumnAction&quot;,
        ///			&quot;ColumnName&quot;: &quot;Customer Id&quot;,
        ///			&quot;Position&quot;: 1,
        ///			&quot;IsHeader&quot;: false,
        ///			&quot;OutputName&quot;: &quot;Customer Id&quot;,
        ///			&quot;OutputType&quot;: &quot;System.Guid&quot;
        ///		},
        ///		{
        ///			&quot;Type&quot;: &quot;DefaultColumnAction&quot;,
        ///			&quot;ColumnName&quot;: &quot;First Name&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string default_reader_config {
            get {
                return ResourceManager.GetString("default_reader_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;NotifyAfter&quot;: 10,  
        ///  &quot;Transformations&quot;: [
        ///    {
        ///      &quot;Condition&quot;: &quot;item[\&quot;Index\&quot;] &gt; 101&quot;,
        ///      &quot;Actions&quot;: [
        ///        {
        ///          &quot;FieldMappings&quot;: {
        ///            &quot;Copy From Salary&quot;: {
        ///              &quot;Value&quot;: &quot;item[\&quot;Salary\&quot;]&quot;,
        ///              &quot;IsDynamic&quot;: true
        ///            },
        ///            &quot;Country&quot;: {
        ///              &quot;Value&quot;: &quot;Brasil&quot;,
        ///              &quot;IsDynamic&quot;: false
        ///            },
        ///            &quot;Calc with Index&quot;: {
        ///              &quot;Value&quot;: &quot;item[\&quot;Index\&quot;] + 100&quot;,
        ///              &quot;IsDynamic&quot;:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dynamic_transform_over_default_csv_config {
            get {
                return ResourceManager.GetString("dynamic_transform_over_default_csv_config", resourceCulture);
            }
        }
    }
}
